import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

typedef Widget WidgetConstructor();

final constructors = <WidgetConstructor>[
  () => new Align(),
  () => new AppBar(),
  () => new AspectRatio(aspectRatio: null),
  () => new Baseline(baseline: null, baselineType: null),
  () => new BackdropFilter(filter: null),
  () => new Banner(message: null, location: null),
  () => new BottomNavigationBar(items: []),
  () => new Card(),
  () => new Checkbox(value: null, onChanged: null),
  () => new Chip(label: null),
  () => new CircularProgressIndicator(),
  () => new ConstrainedBox(constraints: null),
  () => new CupertinoButton(child: null, onPressed: null),
  () => new CupertinoNavigationBar(middle: null),
  () => new CupertinoScaffold(child: null),
  () => new CupertinoSlider(value: 0.0, onChanged: null),
  () => new CupertinoSwitch(value: false, onChanged: null),
  () => new CupertinoTabBar(items: []),
  () => new CustomPaint(),
  () => new DayPicker(
      selectedDate: null,
      currentDate: null,
      onChanged: null,
      firstDate: null,
      lastDate: null,
      displayedMonth: null),
  () => new Draggable(child: null, feedback: null),
  () => new DragTarget(builder: null),
  () => new Drawer(),
  () => new DropdownButton(items: null, onChanged: null),
  () => new EditableText(
      controller: null, focusNode: null, style: null, cursorColor: null),
  () => new ErrorWidget(null),
  () => new FlatButton(child: null, onPressed: null),
  () => new Flex(direction: null),
  () => new FloatingActionButton(child: null, onPressed: null),
  () => new FractionallySizedBox(),
  () => new Hero(tag: null, child: null),
  () => new Icon(Icons.add),
  () => new Image(image: null),
  () => new LimitedBox(),
  () => new LinearProgressIndicator(),
  () => new ListView(),
  () => new MaterialButton(onPressed: null),
  () => new MonthPicker(
      selectedDate: null, onChanged: null, firstDate: null, lastDate: null),
  () => new Offstage(),
  () => new Opacity(opacity: null),
  () => new OverflowBox(),
  () => new Overlay(),
  () => new Padding(padding: null),
  () => new PopupMenuButton(itemBuilder: null),
  () => new Positioned(child: null),
  () => new PreferredSize(child: null, preferredSize: null),
  () => new Radio(value: null, groupValue: null, onChanged: null),
  () => new RaisedButton(onPressed: null),
  () => new RawImage(),
  () => new RichText(text: new TextSpan()),
  () => new RotatedBox(quarterTurns: null),
  () => new Scaffold(),
  () => new ShaderMask(shaderCallback: null),
  () => new SizedBox(),
  () => new SnackBar(content: null),
  () => new Stepper(steps: null),
  () => new Slider(value: 0.0, onChanged: null),
  () => new SliverAppBar(),
  () => new Switch(value: false, onChanged: null),
  () => new OverflowBox(),
  () => new Tab(),
  () => new TabBar(tabs: []),
  () => new Table(),
  () => new Text(""),
  () => new TextField(),
  () => new Title(child: null),
  () => new Tooltip(message: null, child: null),
  () => new Transform(transform: null),
  () => new Viewport(offset: null),
  () => new Wrap(),
  () => new YearPicker(
      selectedDate: null, onChanged: null, firstDate: null, lastDate: null),
];